image: node:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build:
  stage: build
  artifacts:
    untracked: true
  cache:
    paths:
      - node_modules/
  script:
    - rm ./package-lock.json
    - yarn install
    - yarn run build
    - ls -al
    
deploy-dev:
  stage: deploy
  dependencies:
    - build
  script:
    - apt-get update -qq && apt-get install -y -qq zip
    - eval "$(ssh-agent -s)"
    - echo "$SSH_DEV_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "Deploying to dev environment"
    - ssh -o StrictHostKeyChecking=no $SSH_DEV_USERNAME@$SSH_DEV_HOST -p $SSH_DEV_PORT "rm -rf /var/www/datepoll-dev/*"
    - scp -P $SSH_DEV_PORT -o StrictHostKeyChecking=no -rp ./build/* $SSH_DEV_USERNAME@$SSH_DEV_HOST:/var/www/datepoll-dev/ > /dev/null
    - echo "Uploading dev release zip"
    - zip -r DatePollSystems-Home-dev.zip ./build >> /dev/null
    - scp -P $SSH_DEV_PORT -o StrictHostKeyChecking=no ./DatePollSystems-Home-dev.zip $SSH_DEV_USERNAME@$SSH_DEV_HOST:/var/www/datepoll-share/DatePollSystems-Home/ > /dev/null
  only:
    - develop

deploy-prod:
  stage: deploy
  dependencies:
    - build
  script:
    - apt-get update -qq && apt-get install -y -qq zip
    - eval "$(ssh-agent -s)"
    - echo "$SSH_DEV_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -o StrictHostKeyChecking=no $SSH_DEV_USERNAME@$SSH_DEV_HOST -p $SSH_DEV_PORT "rm -rf /var/www/datepoll/*"
    - scp -P $SSH_DEV_PORT -o StrictHostKeyChecking=no -rp ./build/* $SSH_DEV_USERNAME@$SSH_DEV_HOST:/var/www/datepoll/ > /dev/null
    - version=$(git describe --tags $(git rev-list --tags --max-count=1))
    - echo "Uploading prod release zip"
    - zip -r DatePollSystems-Home-latest.zip ./build >> /dev/null
    - cp DatePollSystems-Home-latest.zip "DatePollSystems-Home-${version}.zip"
    - scp -P $SSH_DEV_PORT -o StrictHostKeyChecking=no ./DatePollSystems-Home-latest.zip $SSH_DEV_USERNAME@$SSH_DEV_HOST:/var/www/datepoll-share/DatePollSystems-Home/ > /dev/null
    - scp -P $SSH_DEV_PORT -o StrictHostKeyChecking=no "DatePollSystems-Home-${version}.zip" $SSH_DEV_USERNAME@$SSH_DEV_HOST:/var/www/datepoll-share/DatePollSystems-Home/ > /dev/null
  only:
    - tags
  except:
    - branches
