image: node:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn install
    - yarn run build
    - cd build && ls -al

deploy-dev:
  stage: deploy
  script:
    - eval "$(ssh-agent -s)"
    - echo "$SSH_DEV_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -o StrictHostKeyChecking=no $SSH_DEV_USERNAME@$SSH_DEV_HOST -p $SSH_DEV_PORT "rm -rf /var/www/datepoll-dev/*"
    - scp -P $SSH_DEV_PORT -o StrictHostKeyChecking=no -rp ./build/* $SSH_DEV_USERNAME@$SSH_DEV_HOST:/var/www/datepoll-dev/ > /dev/null
  only:
    - develop

deploy-prod:
    stage: deploy
    script:
      - eval "$(ssh-agent -s)"
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST -p $SSH_PORT "rm -rf /var/www/datepoll/*"
      - scp -P $SSH_PORT -o StrictHostKeyChecking=no -rp ./build/* $SSH_USERNAME@$SSH_HOST:/var/www/datepoll > /dev/null
    only:
      - master
